version: '3'

services:
  
  phpapache:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html
    expose:
      - 80
    ports:
      - 80:80

  mariadb:
    build:
      context: ./importBBDD
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=Nofre
      - MYSQL_DATABASE=Proves
      - MYSQL_USER=Nofre
      - MYSQL_PASSWORD=Nofre
    expose:
      - 3306
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=300M
    expose:
      - 8083
    ports:
      - 8083:80
  



  
